include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_underscores: ignore
    use_null_aware_elements: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    use_key_in_widget_constructors: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_string_interpolations: true

