include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_underscores: ignore
    use_null_aware_elements: ignore

linter:
  rules:
    avoid_print: true
